# mysql-helm-values.yaml
## Use com: helm install mysql bitnami/mysql -f mysql-helm-values.yaml
architecture: standalone
auth:
  rootPassword: "123mudar"
  database: "wordpress"
  username: "wordpress"
  password: "123mudar"
  forcePassword: false
primary:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "microk8s-hostpath"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  configuration: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    innodb_buffer_pool_size=256M
    max_connections=100
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    
    [client]
    default-character-set=utf8mb4
service:
  type: ClusterIP
  port: 3306
