apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-env
data:
  WORDPRESS_DB_HOST: mysql.db.svc
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: 123mudar
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_CACHE_HOST: redis-master.cache.svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:php8.2-apache
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: wordpress-env
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
